version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - "./qdrant_storage:/qdrant/storage"
  
  ilias-web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    container_name: ilias-web
    restart: always
    depends_on:
      - qdrant
    ports:
      - "7000:7000"
    environment:
      ILIAS_PORT: 7000
      JWT_SECRET: ${JWT_SECRET}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_COLLECTION: dev
      ALLOW_REGISTRATION: true
  
  ilias-discord:
    build: 
      context: .
      dockerfile: Dockerfile.discord
    container_name: ilias-discord
    restart: always
    depends_on:
      - qdrant
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_DEV_GUILD: ${DISCORD_DEV_GUILD}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_COLLECTION: dev
      ILIAS_PORT: 7000
      ILIAS_HOST: ilias-web