#syntax=docker/dockerfile:1

FROM node:20-bookworm-slim AS builder


RUN npm install typescript -g
WORKDIR /app/
COPY . .
RUN chown -R node:node /app
USER node
#Install all dependencies
RUN npm ci
RUN npm run tailwind:css
RUN tsc
RUN mv ./build/* /app/ && \
    rm -rf ./public/css/tailwind.css && \
    rm -rf ./src/
RUN npm prune --omit=dev
EXPOSE 7000
ENTRYPOINT ["node", "/app/index.js"]  